<?php

$this->setup(array(
    'title' => 'Edit Booking-Bill',
    'panel' => 'centered-panel',
    'back' => array(
        'Booking-Bill' => $this->url('user/bookings/bills', ['bid' => $this->booking->need('bid')]),
    ),
));

$last_vat_gross = 1;
$last_vat_rate = 19;

?>

<div>
    <h1><?= $this->t('Edit Booking-Bill') ?></h1>

    <div class="separator-small"></div>

    <form method="post">
        <p>
            <div class="default-form-label-top gray">
                <label for="ebf-status"><?= $this->t('Billing status') ?>:</label>
            </div>
            <?= $this->t(sprintf('%s',
            '<select name="ebf-status">' . $this->formSelect()->renderOptions(
                $this->bookingStatusService->getStatusTitles(), array($this->booking->getBillingStatus())) . '</select>')) ?></p>

        <table class="default-table middle-table zebra-table">

            <?php foreach ($this->bills as $bill): ?>
                <tr>
                    <td>
                        <div class="default-form-label-top gray">
                            <label for="ebf-<?= $bill->need('bbid') ?>-description"><?= $this->t('Description') ?></label>
                        </div>
                        <input type="text" name="ebf-<?= $bill->need('bbid') ?>-description" value="<?= $bill->get('description') ?>" style="width: 220px;">
                    </td>

                    <td>
                        <div class="default-form-label-top gray">
                            <label for="ebf-<?= $bill->need('bbid') ?>-time"><?= $this->t('Time (in minutes)') ?></label>
                        </div>
                        <input type="text" name="ebf-<?= $bill->need('bbid') ?>-time" value="<?= ($bill->get('time') ? ($bill->get('time') / 60) : '') ?>" style="width: 64px; text-align: right;">
                    </td>

                    <td>
                        <div class="default-form-label-top gray">
                            <label for="ebf-<?= $bill->need('bbid') ?>-quantity"><?= $this->option('subject.square.unit.plural') ?></label>
                        </div>
                        <input type="text" name="ebf-<?= $bill->need('bbid') ?>-quantity" value="<?= $bill->get('quantity') ?>" style="width: 64px; text-align: right;">
                    </td>

                    <td>
                        <div class="default-form-label-top gray">
                            <label for="ebf-<?= $bill->need('bbid') ?>-quantity"><?= $this->t('Price (in cent)') ?></label>
                        </div>
                        <input type="text" name="ebf-<?= $bill->need('bbid') ?>-price" value="<?= $this->currencyFormat($bill->get('price') / 100) ?>" style="width: 64px; text-align: right;">

                        <?php

                        $last_vat_gross = $bill->get('gross');
                        $last_vat_rate = $bill->get('rate');

                        echo '<select name="ebf-' . $bill->need('bbid') . '-vat-gross" style="width: 60px;">';

                        echo $this->formSelect()->renderOptions(array(
                            '0' => $this->t('plus'),
                            '1' => $this->t('including'),
                        ), array(
                            $last_vat_gross,
                        ));

                        echo '</select>';

                        ?>

                        <input type="text" name="ebf-<?= $bill->need('bbid') ?>-vat-rate" value="<?= $last_vat_rate ?>" style="width: 20px; text-align: right;"> % <?= $this->t('VAT') ?>
                    </td>

                    <td style="vertical-align: bottom;">
                        <a href="?delete=<?= $bill->need('bbid') ?>" class="unlined gray symbolic symbolic-cross"></a>
                    </td>
                </tr>
            <?php endforeach; ?>

            <tr>
                <td>
                    <div class="default-form-label-top gray">
                        <label for="ebf-new-description"><?= $this->t('Description') ?></label>
                    </div>
                    <input type="text" name="ebf-new-description" placeholder="<?= $this->t('New position') ?>" style="width: 220px;">
                </td>

                <td class>
                    <div class="default-form-label-top gray">
                        <label for="ebf-new-time"><?= $this->t('Time (in minutes)') ?></label>
                    </div>
                    <input type="text" name="ebf-new-time" style="width: 64px; text-align: right;">
                </td>

                <td>
                    <div class="default-form-label-top gray">
                        <label for="ebf-new-quantity"><?= $this->option('subject.square.unit.plural') ?></label>
                    </div>
                    <input type="text" name="ebf-new-quantity" style="width: 64px; text-align: right;">
                </td>

                <td colspan="2">
                    <div class="default-form-label-top gray">
                        <label for="ebf-new-quantity"><?= $this->t('Price (in cent)') ?></label>
                    </div>
                    <input type="text" name="ebf-new-price" style="width: 64px; text-align: right;">

                    <?php

                    echo '<select name="ebf-new-vat-gross" style="width: 60px;">';

                    echo $this->formSelect()->renderOptions(array(
                        '0' => $this->t('plus'),
                        '1' => $this->t('including'),
                    ), array(
                        $last_vat_gross,
                    ));

                    echo '</select>';

                    ?>

                    <input type="text" name="ebf-new-vat-rate" value="<?= $last_vat_rate ?>" style="width: 20px; text-align: right;"> % <?= $this->t('VAT') ?>
                </td>
            </tr>

            <tr>
                <td colspan="5">
                    <a href="?create=default-bill" class="symbolic symbolic-plus-link-white"><?= $this->t('New position by using the pricing rules for this booking') ?></a>
                </td>
            </tr>
        </table>

        <div class="separator-small"></div>

        <div class="centered-text">
            <input type="submit" name="ebf-save" value="<?= $this->t('Save') ?>" class="default-button">
            &nbsp;
            <input type="submit" name="ebf-save-and-back" value="<?= $this->t('Save and back') ?>" class="default-button">
        </div>
    </form>
</div>
