<?php

$this->setup(array(
    'title' => 'Booking-Statistic',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'Booking-Administration' => $this->url('backend/booking'),
        'User-Statistic' => $this->url('backend/user/stats'),
        'Event-Statistic' => $this->url('backend/event/stats'),
    ),
));

echo $this->BackendBookingsStats($this->stats);

?>