version: '3'
services:
  database:
    image: mariadb:10.6.8
    expose:
      - 3306
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=booking
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    expose:
      - 9000
    volumes:
      - ./:/var/www
  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8090:80"
  nginx:
    build:
      context: .
    restart: always
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - php