version: '3'
services:
  database:
    image: mariadb:10.6.8
    expose:
      - 3306
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=booking
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - "8085:80"
    volumes:
      - ./:/var/www
  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8090:80"