<?php

$this->setup(array(
    'title' => 'Event-Statistic',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'Event-Administration' => $this->url('backend/event'),
        'User-Statistic' => $this->url('backend/user/stats'),
        'Booking-Statistic' => $this->url('backend/booking/stats'),
    ),
));

$enabled = 0;

foreach ($this->stats as $stat) {
    $var = $stat['status'];
    $$var += $stat['count'];
}

$total = $enabled;

?>

<div>
    <h1><?= $this->t('Event-Statistic') ?></h1>

    <div class="separator separator-line"></div>

    <table class="bordered-table">
        <tr>
            <td><b><?= $this->t('Events') ?></b></td>
            <td class="right-text"><b><?= $this->numberFormat($total) ?></b></td>
        </tr>

        <tr>
            <td><?= $this->t('Enabled') ?></td>
            <td class="right-text">
                <?= $this->numberFormat($enabled) ?>
            </td>
        </tr>
    </table>
</div>