<?php

$this->setup(array(
    'title' => 'Pricing',
    'panel' => 'centered-panel giant-sized',
    'back' => array(
        'Configuration' => $this->url('backend/config'),
    ),
));

$this->headScript()->appendFile($this->basePath('js/controller/backend/config-square/pricing.min.js'));

?>

<div style="width: 100%;">
    <h1><?= $this->t('Pricing') ?></h1>

    <div class="separator-small"></div>

    <p><?= sprintf($this->t('How much do bookings cost for your %s?'), $this->option('subject.square.type.plural')) ?></p>

    <div class="separator separator-line"></div>

    <style type="text/css">
        .datepicker { width: 75px; } 
        .timepicker { width: 39px; }
        .pricepicker { width: 50px; color: #333 !important; font-weight: bold; text-align: right; }
        .timeblockpicker { width: 25px; text-align: right; }

        .pricing-grammar { margin: 0 6px; cursor: default; }
        .pricing-grammar:last-child { margin: 0 0 0 6px; }

        .pricing-type { margin: 0 6px; cursor: default; }
        .pricing-type:last-child { margin: 0 0 0 6px; }

        .pricing-delete { color: #777 !important; text-decoration: none; cursor: pointer; }
        .pricing-delete:hover { color: #333; }

        .default-table td { padding-bottom: 3px !important; }

        #pricing-table-template { display: none; }

        .pricing-table-day-range { background: #defcf9; }
        .pricing-table-time-range { background: #b5f7f0; }
        .pricing-table-price-range { background: #7af5e7;  }

        @media screen and (max-width: 1024px)
        {
            .pricing-table-day-range { display: block; }
            .pricing-table-time-range { display: block; }
            .pricing-table-price-range { display: block;  }
            
        }

        .bordered-table-background { background: red; }

         tr:not(:last-child) > td > .pricing-price-new {
            display: none;
        }

        .date-range-error, .time-range-error, .price-error, .time-block-error {
            display: none;
            font-weight: bold;
            color: red;
        }

        .date-range-error.visible, .time-range-error.visible, 
        .price-error.visible, .time-block-error.visible {
            display: block;
        }

        input.invalid {
            border-color: red;
            background-color: #f2b7a5;
        }

    </style>

    <script type="text/javascript">
        <?php

        $jsRules = array();

        foreach ($this->squaresPricingRules as $pricingRule) {
            $jsRule = array();

            foreach ($pricingRule as $key => $value) {
                if ($key == 'date_start' || $key == 'date_end') {
                    $value = $this->dateFormat(new \DateTime($value), IntlDateFormatter::MEDIUM, null, null, $this->t('dd.MM.yyyy'));
                }

                $jsRule[] = '"' . $value . '"';
            }

            $jsRules[] = '[ ' . implode(', ', $jsRule) . ' ]';
        }

        ?>

        var timeBlock = <?= $this->squaresTimeBlock ?>;
        var minStart = <?= $this->squaresMinStartTime ?>;
        var maxEnd = <?= $this->squaresMaxEndTime ?>;
        var pricingRules = [ <?= implode(', ', $jsRules) ?> ];
    </script>

    <div id="pricing-table-template">
        <table><tbody>
            <tr>
                <td class="pricing-date-range">
                    <input type="text" value="" class="pricing-dateStart datepicker"><span class="pricing-grammar"><?= $this->t('to') ?></span><input type="text" value="" class="pricing-dateEnd datepicker">
                    <span class="date-range-error"><br><br><?= $this->t('Invalid date') ?></span>
                </td>
                <td>
                    <table class="pricing-table-day-range"><tbody>
                        <tr>
                            <td>
                                <table><tbody>
                                    <tr>
                                        <td class="pricing-day-range">
                                            <?php

                                            $days = array('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday');

                                            echo '<select class="pricing-dayStart">';
                                            foreach ($days as $index => $day) echo '<option value="' . $index . '"' . ($index == 0 ? ' selected="selected"' : '') . '>' . $this->t($day) . '</option>';
                                            echo '</select>';

                                            echo '<span class="pricing-grammar">' . $this->t('to') . '</span>';

                                            echo '<select class="pricing-dayEnd">';
                                            foreach ($days as $index => $day) echo '<option value="' . $index . '"' . ($index == 4 ? ' selected="selected"' : '') . '>' . $this->t($day) . '</option>';
                                            echo '</select>';

                                            ?>
                                        </td>
                                        <td>
                                            <a href="#" class="pricing-day-range-new unlined gray"><em><span class="symbolic symbolic-plus"><?= $this->t('New day') ?></span></em></a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>
                                            <table class="pricing-table-time-range"><tbody>
                                                <tr>
                                                    <td>
                                                        <table><tbody>
                                                            <tr>
                                                                <td class="pricing-time-range">
                                                                    <input type="text" value="06:00" maxlength="5" class="pricing-timeStart timepicker"><span class="pricing-grammar"><?= $this->t('to') ?></span><input type="text" value="24:00" maxlength="5" class="pricing-timeEnd timepicker"><span class="pricing-grammar"><?= $this->t('Clock') ?></span>
                                                                    <span class="time-range-error"><br><?= $this->t('Invalid time') ?></span>
                                                                </td>
                                                                <td>
                                                                    <a href="#" class="pricing-time-range-new unlined"><em><span class="symbolic symbolic-plus"><?= $this->t('New time') ?></span></em></a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>
                                                                    <table class="pricing-table-price-range"><tbody>
                                                                        <tr>
                                                                            <td class="pricing-price">
                                                                                <?php

                                                                                echo '<input type="text" value="0,00" maxlength="6" class="pricing-price-number pricepicker"><span class="pricing-grammar">' . $this->config('i18n.currency') . '</span>';

                                                                                echo '<select class="pricing-rate-gross" style="width: 60px;">';
                                                                                echo '<option value="0">' . $this->t('plus') . '</option>';
                                                                                echo '<option value="1" selected="selected">' . $this->t('including') . '</option>';
                                                                                echo '</select>';

                                                                                echo '<input type="text" value="' . $this->option('service.vat') . '" maxlength="3" class="pricing-rate" style="width: 20px;">';
                                                                                echo '<span class="pricing-grammar">% ' . $this->t('VAT') . '</span>';
                                                                                echo '<span class="price-error"><br>' . $this->t('Invalid value') . '</span>';
                                                                                echo '<br><span class="pricing-type">' . $this->t('booking type') . '</span>';
                                                                                echo '<select class="pricing-type">';
                                                                                echo '<option value="null">' . $this->t('All') . '</option>';
                                                                                echo '<option value="1">' . $this->t('Single') . '</option>';
                                                                                if ($this->option('service.allow.subscription.price')) {
                                                                                    echo '<option value="2">' . $this->t('Subscription') . '</option>';
                                                                                }
                                                                                if ($this->option('service.allow.club-card.price')) {
                                                                                    echo '<option value="3">' . $this->t('Club Card') . '</option>';
                                                                                }
                                                                                echo '</select>';                                                                                
                                                                                echo '<br><span class="pricing-grammar">' . $this->t('valid for') . '</span>';

                                                                                echo '<select class="pricing-sid">';
                                                                                echo '<option value="null">' . sprintf($this->t('All %s'), $this->option('subject.square.type.plural')) . '</option>';
                                                                                foreach ($this->squares as $square) {
                                                                                    echo '<option value="' . $square->get('sid') . '">' . $this->option('subject.square.type') . ' ' . $square->get('name') . '</option>';
                                                                                }
                                                                                echo '</select>';

                                                                                echo '<span class="pricing-grammar">' . $this->t('and') . '</span>';
                                                                                echo '<input type="text" value="' . round($this->squaresTimeBlock / 60) . '" maxlength="3" class="pricing-timeBlock timeblockpicker">';
                                                                                echo '<span class="pricing-grammar">' . $this->t("Min.") . '</span>';
                                                                                echo '<span class="time-block-error"><br>' . $this->t('Invalid value') . '</span>';

                                                                                ?>
                                                                            </td>
                                                                            <td>
                                                                                <a href="#" class="pricing-price-new unlined"><em><span class="symbolic symbolic-plus"><?= $this->t('New price') ?></span></em></a>
                                                                                <br><br>
                                                                                <a href="#" class="pricing-grammar pricing-delete tooltip"><span class="symbolic symbolic-cross"></span></a>
                                                                            </td>
                                                                        </tr>
                                                                    </tbody></table>
                                                                </td>
                                                            </tr>
                                                        </tbody></table>
                                                    </td>
                                                </tr>
                                            </tbody></table>
                                        </td>
                                    </tr>
                                </tbody></table>
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>
        </tbody></table>
    </div>

    <div id="pricing-table">
        <table class="bordered-table">
            <tr>
                <td>
                    <a href="#" class="pricing-date-range-new unlined   "><em><span class="symbolic symbolic-plus"><?= $this->t('New period') ?></span></em></a>
                </td>
            </tr>
        </table>
    </div>

    <div class="separator separator-line"></div>

    <div class="centered-text">
        <form method="post" action="<?= $this->url('backend/config/square/pricing') ?>" id="pricing-form">
            <div id="pricing-form-rules"></div>

            <div class="sandbox">
                <table class="default-table">
                    <tr>
                        <td class="default-form-label-row">
                            <label for="pricing-visibility"><?= $this->t('Display pricing:') ?></label>
                        </td>
                        <td>
                            <?php

                            $element = new \Laminas\Form\Element\Select('pricing-visibility');
                            $element->setAttribute('id', 'pricing-visibility');
                            $element->setValueOptions(array(
                                'never' => 'For no one',
                                'private' => 'For users',
                                'public' => 'For users and visitors',
                            ));
                            $element->setValue($this->option('service.pricing.visibility', 'never'));

                            echo $this->formSelect($element);

                            ?>
                        </td>
                    </tr>
                </table>
            </div>

            <div class="separator separator-line"></div>

            <input type="hidden" name="pricing-rules-count" id="pricing-rules-count" value="0">
            <input type="submit" id="pricing-save" value="<?= $this->t('Save') ?>" class="default-button">
        </form>
    </div>
</div>
