<?php

$this->setup(array(
    'title' => 'My bookings',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'My account' => $this->url('user/settings'),
    ),
));

$this->headScript()->appendFile($this->basePath('js/controller/user/bookings.min.js'));

?>


<div>
    <h1><?= $this->t('My bookings') ?></h1>

    <div class="separator-small"></div>

    <?= $this->userBookingsCount($this->bookings) ?>
    <?php if (count($this->bookings) > 0): ?>

        <div class="separator separator-line"></div>

        <style type="text/css">
            .default-table td { padding-right: 16px; padding-bottom: 8px; height: 24px; }
        </style>

            <div class="accordion js-accordion">
                <div class="accordion__item js-accordion-item">
                    <div class="accordion-header js-accordion-header"><?= $this->t('Past bookings') ?></div> 
                    <div class="accordion-body js-accordion-body">
                        <div class="accordion-body__contents">
                            <table class="default-table middle-table">

            <?php

            $todayMentioned = false; 

            foreach ($reservations as $reservation) {

                $booking = $reservation->needExtra('booking');
                $bookingDateTimeStart = new DateTime($reservation->need('date') . ' ' . $reservation->need('time_start'));
                $bookingDateTimeEnd = new DateTime($reservation->need('date') . ' ' . $reservation->need('time_end'));

                $cancellable = false;
                $classes = array();

                $square = $this->squareManager->get($booking->need('sid'));

                if ($this->now < $bookingDateTimeStart) {
                    $classes['color'] = 'gray';

                    if (! $todayMentioned) {
                        echo '</table></div></div></div>';
                        echo '<div class="accordion__item js-accordion-item">';
                        $text = $this->t('Next bookings');
                        echo '<div class="accordion-header js-accordion-header">' . $text . '</div>';
                        echo '<div class="accordion-body js-accordion-body">';
                        echo '<div class="accordion-body__contents">';
                        echo '<table class="default-table middle-table">';                            
            
                        $todayMentioned = true;
                    }
                    $cancellable = $this->squareValidator->isCancellable($booking, $reservation);
                } 

                $bills = $booking->getExtra('bills');

                if ($bills) {
                    $price = 0;

                    foreach ($bills as $bill) {
                        $price += $bill->need('price');
                    }

                    $pricing = '';
                    $pricing .= '<a href="' . $this->url('user/bookings/bills', ['bid' => $booking->need('bid')]) . '" class="default-button mini-button" style="min-width: 80px;">';
                    $pricing .= $this->priceFormat($price);
                    $pricing .= '</a>';
                } else {
                    $pricing = '<div class="centered-text gray">&middot;</div>';
                }

                echo '<tr>';

                $class = implode(' ', $classes);

                echo '<td class="' . $class . (! isset($classes['color']) ? 'my-highlight' : '') . '">' . $this->option('subject.square.type') . ' ' . $this->t($square->need('name')) . '</td>';
                echo '<td class="' . $class . '">' . $this->dateRange($bookingDateTimeStart, $bookingDateTimeEnd) . '</td>';
                echo '<td class="' . $class . '" style="padding-left: 16px;">' . $pricing . '</td>';

                if ($cancellable) {
                    echo sprintf('<td style="padding-left: 16px;"><a href="%s" class="default-button mini-button">%s</a></td>',
                        $this->url('square/booking/cancellation', [], ['query' => ['bid' => $booking->need('bid')]]), $this->t('Cancel booking'));
                } else {
                    echo '<td class="centered-text gray" style="padding-left: 16px;">&middot;</td>';
                }

                echo '</tr>';
            }

            ?>
        </table>
        </div>
        </div>
        </div>
        </div>

        <div class="separator-small"></div>

    <?php endif; ?>

</div>