<!DOCTYPE html>
<html lang="<?= $this->config('i18n.locale') ?>">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="format-detection" content="telephone=no">
        <meta name="generator" content="<?= $this->option('service.branding.name') ?>">
        <meta name="publisher" content="<?= $this->option('client.name.full') ?>">
        <meta name="description" content="<?= $this->option('service.meta.description') ?>">
        <link type="image/x-icon" rel="icon" href="<?= $this->basePath('imgs-client/icons/fav.ico') ?>">
        <link type="image/x-icon" rel="shortcut icon" href="<?= $this->basePath('imgs-client/icons/fav.ico') ?>">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/jquery-ui/jquery-ui.min.css') ?>" media="all">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/ionicons.css') ?>" media="all">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css/default.min.css') ?>" media="all">
        <link type="text/css" rel="stylesheet" href="<?= $this->basePath('css-client/default.css') ?>" media="all">

        <?= $this->headLink() ?>
        <?= $this->headTitle($this->option(['client.name.short', 'service.name.full']))->setSeparator(' &middot; ')->setAutoEscape(false) ?>
    </head>

    <body>
        <?php $user = $this->getHeaderUser(); ?>
        <div id="header" class="no-wrap no-print" <?= $this->headerAttributes() ?>>
            <div class="hamburger-menu">
                <input id="menu__toggle" type="checkbox" />
                <label class="menu__btn" for="menu__toggle">
                    <span></span>
                </label>

                <ul class="menu__box">
                    <li>
                        <a href="<?= $this->basePath('/') ?>" class="default-button"?><span class="symbolic symbolic-date"><?= $this->t('Calendar') ?></span></a>
                    </li>
                    <?php if ($user): ?>
                        <?php if ($user->can('admin.see-menu')): ?>                    
                            <li>
                            <a href="<?= $this->url('backend') ?>" id="admin-header-link" class="default-button"><span class="symbolic symbolic-config"><?= $this->t('Administration') ?></span></a>
                            </li>
                        <?php endif; ?>
                        <li>
                            <a href="<?= $this->url('user/bookings') ?>" class="default-button"><span class="symbolic symbolic-booking"><?= $this->t('My bookings') ?></span></a>
                        </li>
                        <li>
                            <a href="<?= $this->url('user/settings') ?>" class="default-button"><span class="symbolic symbolic-user"><?= $this->t('My account') ?></span></a>
                        </li>
                        <li>
                            <a href="<?= $this->url('user/logout') ?>" class="default-button"><span class="symbolic symbolic-off"><?= $this->t('Logout') ?></span></a>
                        </li>
                        <li>
                            <a href="<?= $this->url('service/help') ?>" class="default-button" data-tooltip="<?= sprintf($this->t('Get additional %shelp and information%s'), '<b>', '</b>') ?>"><b>?</b></a>
                        </li>
                    <?php else: ?>
                        <li>
                            <?php echo sprintf($this->t('To book %s, %splease register first%s'),
                                $this->option('subject.square.type.plural'),
                                '<br><a href="' . $this->url('user/registration') . '" class="symbolic symbolic-plus-link">', '</a>');
                            ?>
                        </li>
                        <li>
                            <?= sprintf($this->t('or simply %s login here'), '<br>') ?>
                        </li>
                        <li>
                            <a href="<?= $this->url('user/login') ?>" class="default-button"><span class="symbolic symbolic-user"><?= $this->t('Login') ?></span></a>
                        </li>
                    <?php endif; ?>
                </ul>
                <?= $this->headerLocaleChoice() ?>
                <a href="<?= $this->basePath('/') ?>" id="logo"></a>
                <a href="tel:<?= $this->option('client.contact.phone') ?>">
                    <i class="symbolic symbolic-phone"></i>
                </a>
            </div>        
            <div id="label">
                <a href="<?= $this->basePath('/') ?>" id="logo"></a>

                <div id="label-client"><?= $this->option('client.name.full') ?></div>
                <div id="label-service"><?= $this->option('service.name.full') ?></div>

                <?php if ($this->option('service.branding', 'true') == 'true'): ?>
                    <div id="branding">&raquo; <?= sprintf($this->t('Powered by %s'), '<a href="' . $this->option('service.branding.website') .'" target="_blank">' . $this->option('service.branding.name') . '</a>') ?></div>
                <?php else: ?>
                    <style type="text/css"> #label-client { margin-top: 15px; } </style>
                <?php endif; ?>
            </div>

            <div id="topbar">
                <?= $this->headerLocaleChoice() ?>

                <div id="topbar-website" class="responsive-pass-4">
                    <p>
                        <span class="header-light"><?= $this->t('Our website') ?></span><br>
                        <span class="large-text">
                            <a href="<?= $this->option('client.website') ?>" class="unlined header-white">
                                <?= $this->shortUrl($this->option('client.website')) ?>
                            </a>
                        </span>
                    </p>
                </div>

                <div id="topbar-phone" class="responsive-pass-4">
                    <p>
                        <span class="header-light"><?= $this->t('Book by phone') ?></span><br>
                        <span class="large-text">
                            <a href="tel:<?= $this->option('client.contact.phone') ?>" class="unlined header-white">
                                <?= $this->option('client.contact.phone') ?>
                            </a>
                        </span>
                    </p>
                </div>

                <div id="topbar-separator" class="responsive-pass-4"></div>
            </div>
        </div>

        <div id="content">
            <?= $this->messages() ?>

            <?= $this->tabs() ?>

            <div class="content-panel <?= $this->placeholder('panel') ?>">
                <?= $this->content ?>
            </div>

            <?= $this->links() ?>

        </div>
        
        <?= $this->partial('base/cookie') ?>
        
        <div id="footer">
            <div class="centered-text">
                <span class="no-wrap header-light">v<?= $this->version() ?> &copy; <?= date('Y') ?> <a href="<?= $this->option('client.website') ?>"><?= $this->option('client.name.full') ?></a></span>
                <span class="header-light">(<a href="<?= $this->option('client.website.imprint') ?>"><?= $this->t('Imprint') ?></a><?php if ($this->option('client.website.privacy')): ?> &ndash; <a href="<?= $this->option('client.website.privacy') ?>"><?= $this->t('Privacy') ?></a><?php endif; ?>)</span>
                <?php if ($this->option('service.branding', 'true') == 'true'): ?><span class="no-wrap">&amp; <a href="<?= $this->option('service.branding.website') ?>"><?= $this->option('service.branding.name') ?></a> (<?= $this->t('Software') ?>)</span><?php endif; ?>
            </div>
        </div>

        <script type="text/javascript" src="<?= $this->basePath('js/jquery/jquery.min.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/jquery-ui/jquery-ui.min.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/default.min.js') ?>"></script>
        <script type="text/javascript" src="<?= $this->basePath('js/cookie-consent.min.js') ?>"></script>
        <?= $this->headScript() ?>
    </body>
</html>
