<?php

$this->setup(array(
    'title' => 'User-Administration',
    'panel' => 'centered-panel large-sized',
    'back' => true,
    'links' => array(
        'User-Statistic' => $this->url('backend/user/stats'),
        'Booking-Administration' => $this->url('backend/booking'),
        'Event-Administration' => $this->url('backend/event'),
        'Configuration' => $this->url('backend/config'),
    ),
));

?>

<div>
    <h1><?= $this->t('User-Administration') ?></h1>

    <div class="separator-small"></div>

    <p><?= $this->t('Here you can create, edit or delete the users of your system.') ?></p>

    <div class="separator separator-line"></div>

    <?= $this->partial('backend/user/index.search.phtml', ['name' => $this->name, 'status' => $this->status, 'email' => $this->email, 'dateActive' => $this->dateActive, 'ip' => $this->ip, 'dateCreated' => $this->dateCreated]) ?>

    <div class="separator separator-line"></div>

    <div class="centered-text" style="padding: 16px 0px 16px 0px;">

        <?php if ($this->users): ?>

            <?= $this->backendUsersFormat($this->users, $this->search) ?>

        <?php else: ?>

            <?php if ($this->search): ?>
                <p><span class="red"><?= sprintf($this->t('%sNo users found%s for this search'), '<b>', '</b>') ?></span></p>
            <?php endif; ?>

            <p><a href="<?= $this->url('backend/user/edit') ?>" class="unlined gray"><span class="symbolic symbolic-plus"><?= $this->t('New user') ?></span></a></p>

        <?php endif; ?>

    </div>
</div>