<?php

$this->headScript()->appendFile($this->basePath('js/controller/backend/user/index.search.min.js'));

?>

<div style="padding: 10px 0px 16px 0px;">
    <form method="get" action="<?= $this->url('backend/user') ?>">
        <table class="default-table">
            <tr>
                <td>
                    <div class="default-form-label-top gray">
                        <label for="usf-name"><?= $this->t('Name or number') ?>:</label>
                    </div>

                    <input type="text" name="usf-name" id="usf-name" value="<?= $this->name ?>" data-autocomplete-url="<?= $this->url('backend/user/interpret') ?>" style="width: 30vw;">
                </td>

                <td style="vertical-align: bottom;">
                    <input type="submit" value="<?= $this->t('Search') ?>" class="default-button">
                </td>

                <td style="vertical-align: bottom; padding-bottom: 7px;">
                    <a href="#" id="usf-filters-link" class="unlined gray"><?= $this->t('Advanced search') ?></a>
                </td>
            </tr>
        </table>

        <div id="usf-filters-box" class="sandbox" style="display: none; margin: 26px auto 0px auto;">
            <table class="default-table" style="margin-left: 0px;">
                <tr>
                    <td style="vertical-align: bottom;">
                        <div class="default-form-label-top gray">
                            <label for="usf-status"><?= $this->t('Status') ?>:</label>
                        </div>                        
                        <?= $this->backendUserStatusList() ?>
                    </td>
                </tr>    
                <tr>
                    <td>
                        <div class="default-form-label-top gray">
                            <label for="usf-email"><?= $this->t('Email') ?>:</label>
                        </div>

                        <input type="text" name="usf-email" id="usf-email" value="<?= $this->email ?>" style="width: 30vw;">
                    </td>                    
                </tr>  
                <tr>    
                    <td style="vertical-align: bottom;">
                        <div class="default-form-label-top gray">
                            <label for="date-active"><?= $this->t('Active') ?>:</label>
                        </div>
                        <?= $this->backendUserOperatorSelect("date-active") ?>  

                        <div class="inline-element">
                            <label for="date-active" class="inline-label symbolic symbolic-date"><span><?= $this->dateFormat($this->dateActive, IntlDateFormatter::MEDIUM, null, null, $this->t('dd.MM.yyyy')) ?></span></label>
                            <input type="text" name="date-active" id="date-active" value="<?= $this->dateFormat($this->dateActive, IntlDateFormatter::MEDIUM, null, null, $this->t('dd.MM.yyyy')) ?>"
                                class="inline-label-container datepicker" style="padding-left: 28px; width: 96px;">
                        </div>    

                    </td>
                </tr>   
                <tr>
                    <td>
                        <div class="default-form-label-top gray">
                            <label for="usf-ip"><?= $this->t('IP') ?>:</label>
                        </div>

                        <input type="text" name="usf-ip" id="usf-ip" value="<?= $this->ip ?>" style="width: 10vw;">
                    </td>                    
                </tr>      
                <tr>    
                    <td style="vertical-align: bottom;">
                        <div class="default-form-label-top gray">
                            <label for="date-created"><?= $this->t('Created') ?>:</label>
                        </div>
                        <?= $this->backendUserOperatorSelect("date-created") ?>  

                        <div class="inline-element">
                            <label for="date-created" class="inline-label symbolic symbolic-date"><span><?= $this->dateFormat($this->dateCreated, IntlDateFormatter::MEDIUM, null, null, $this->t('dd.MM.yyyy')) ?></span></label>
                            <input type="text" name="date-created" id="date-created" value="<?= $this->dateFormat($this->dateCreated, IntlDateFormatter::MEDIUM, null, null, $this->t('dd.MM.yyyy')) ?>"
                                class="inline-label-container datepicker" style="padding-left: 28px; width: 96px;">
                        </div>    

                    </td>
                </tr>                                           
            </table>
        </div>
    </form>
</div>
