<?php

$this->setup(array(
    'title' => 'User-Statistic',
    'panel' => 'centered-panel',
    'back' => true,
    'links' => array(
        'User-Administration' => $this->url('backend/user'),
        'Booking-Statistic' => $this->url('backend/booking/stats'),
        'Event-Statistic' => $this->url('backend/event/stats'),
    ),
));

$placeholder = $deleted = $blocked = $disabled = $enabled = $assist = $admin = 0;

foreach ($this->stats as $stat) {
    $var = $stat['status'];
    $$var += $stat['count'];
}

$total = $deleted + $blocked + $disabled + $enabled + $assist + $admin;

?>

<div>
    <h1><?= $this->t('User-Statistic') ?></h1>

    <div class="separator separator-line"></div>

    <table class="bordered-table">
        <tr>
            <td><?= $this->t('Deleted user') ?></td>
            <td class="right-text">
                <?php if ($deleted) { ?>
                    <a href="<?= $this->url('backend/user', [], ['query' => ['usf-status' => 'deleted']]) ?>">
                <?php } ?>
                        <?= $this->numberFormat($deleted) ?>
                <?php if ($deleted) { ?>
                    </a>
                <?php } ?>
            </td>
        </tr>

        <tr>
            <td><?= $this->t('Blocked user') ?></td>
            <td class="right-text">
                <?php if ($blocked) { ?>
                    <a href="<?= $this->url('backend/user', [], ['query' => ['usf-status' => 'blocked']]) ?>">
                <?php } ?>
                        <?= $this->numberFormat($blocked) ?>
                <?php if ($blocked) { ?>
                    </a>
                <?php } ?>
            </td>
        </tr>

        <tr>
            <td><?= $this->t('Waiting for activation') ?></td>
            <td class="right-text">
                <?php if ($disabled) { ?>
                    <a href="<?= $this->url('backend/user', [], ['query' => ['usf-status' => 'disabled']]) ?>">
                <?php } ?>
                        <?= $this->numberFormat($disabled) ?>
                <?php if ($disabled) { ?>
                    </a>
                <?php } ?>
            </td>
        </tr>

        <tr>
            <td><?= $this->t('Enabled user') ?></td>
            <td class="right-text">
                <?php if ($enabled) { ?>
                    <a href="<?= $this->url('backend/user', [], ['query' => ['usf-status' => 'enabled']]) ?>">
                <?php } ?>
                        <?= $this->numberFormat($enabled) ?>
                <?php if ($enabled) { ?>
                    </a>
                <?php } ?>
            </td>
        </tr>

        <tr>
            <td><?= $this->t('Assist') ?></td>
            <td class="right-text">
                <?php if ($assist) { ?>
                    <a href="<?= $this->url('backend/user', [], ['query' => ['usf-status' => 'assist']]) ?>">
                <?php } ?>
                        <?= $this->numberFormat($assist) ?>
                <?php if ($assist) { ?>
                    </a>
                <?php } ?>
            </td>
        </tr>

        <tr>
            <td><?= $this->t('Admin') ?></td>
            <td class="right-text">
                <?php if ($admin) { ?>
                    <a href="<?= $this->url('backend/user', [], ['query' => ['usf-status' => 'admin']]) ?>">
                <?php } ?>
                        <?= $this->numberFormat($admin) ?>
                <?php if ($admin) { ?>
                    </a>
                <?php } ?>
            </td>
        </tr>

        <tr>
            <td><b><?= $this->t('Users total') ?></b></td>
            <td class="right-text"><b><?= $this->numberFormat($total) ?></b></td>
        </tr>     

        <tr>
            <td><b><?= $this->t('Placeholders total') ?></b></td>
            <td class="right-text"><b>
                <?php if ($placeholder) { ?>
                    <a href="<?= $this->url('backend/user', [], ['query' => ['usf-status' => 'placeholder']]) ?>">
                <?php } ?>
                        <?= $this->numberFormat($placeholder) ?>
                <?php if ($placeholder) { ?>
                </a>
            <?php } ?>
            </b></td>
        </tr>
   
    </table>
</div>